title: Mega Big News
author:
  name: Mega Big News
  email: megabignews@gmail.com
description: |
  All the news you'd rather forget and some of the news you'll never remember.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: auto
