title: Mega Big News
author:
  name: Mega Big News
  email: megabignews@gmail.com
description: |
  Newsing all over you.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
  - disclaimer.md
minima:
  skin: auto
paginate: 20
paginate_path: "/page:num/"
google_analytics: G-L7R80M8SCM
url: https://megabignews.com